# Generated by Django 4.0.6 on 2022-07-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_con_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conection_eg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='con',
        ),
    ]
